quarkus:
  package:
    jar:
      type: uber-jar
      add-runner-suffix: false
  application:
    name: repository-driver-cli
  log:
    category:
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG
#      "org.jboss.pnc.rpm":
#        level: DEBUG
      # Avoids "Invalid cookie header" messages from old httpclient from keycloak from bacon.
      "org.apache.http.client.protocol":
        level: DEBUG
      "org.apache.sshd":
        level: DEBUG
#    console:
#      format: "%d{HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.}] (%t) %s%e mdc:[%X]%n"
  rest-client:
    logging:
      scope: request-response
      body-limit: 50
    repository-driver-service:
      url: "http://localhost:8080"
